### ISSUE TITLE
Use git lfs

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank_notebooks#25]
@Marius1311 
I think it would be best to recreate the repo/purge the history (the second option is preferred) and use git-lfs. I've tested this if it's possible to download the data using `scanpy.read(..., backup_url=...)` and it works.

Pros:
- currently, I download 230MB, which is a bit too much for such a small repo
- it will speedup the download (to run the tutorials, you don't need to download the datasets in the `datasets` directory)
    using `GIT_LFS_SKIP_SMUDGE=1 git clone ...`
-  gallery can be finished (I don't know what the rate limits on figshare are, but with gh, we've never had an issue before)

Cons:
- 1GiB limit: currently, we'd be using ~180MiB (30 for pancres, 150 + pancreas_preprocessed)
- needs git-lfs to download without a warning (see last point in Todos)

Todos:
- [ ] for gallery, we want to download the file only once, so the path should be absolute
- [x] I need to triple authenticate before I push - this will break automatic the travis pipeline in the main repo,
      but this does not happens with a personal access token
- [x] git-lfs has to be installed to "properly" download the repo (i.e. the clone succeeds, the checkout fails - this automatically remove the files and adds the changes to the staging area, ergo we need git-lfs on the main repo travis, which is not an issue)

**Comment by Marius1311** [comment]
Mike, I don't think we need to change anything here since this repository is not meant to be downloaded. This is why we separated cellrank from cellrank_notebooks. This is literally only meant to store our data and tutorials. 

Since there is always a risk of something going wrong when doing these sorts of changes, I would not like us to do this right now and to delay this to later, if really necessary.

**Comment by michalk8** [comment]
I think this is necessary. I need to close this issue.

**Comment by michalk8** [comment]
Note to self: https://christoph.ruegg.name/blog/git-howto-mirror-a-github-repository-without-pull-refs.html

**Comment by michalk8** [comment]
Done via https://github.com/theislab/cellrank_notebooks/commit/62aaa2c2d09eb00e839ac9f4693ec429b7631159.
The commits have been rewritten using, it's very easy to use. I will do the same for the main repo (no git-lfs there, for now).
