### ISSUE TITLE
Reversed direction of trajectory 

### ISSUE THREAD

**Issue by sidrahmaryam** [theislab/cellrank_notebooks#28]
Hello, 
I am facing an issue while running the pipeline. As while running the **scvelo** basic flow, the trajectory shows correct direction, i.e., towards mature cell cluster. 
But when I ran cellrank part of dynamical model, the PAGA plotting shows reverse direction, from **mature to immature**. what might be the reason for same? 

Also, when i am plotting gene trends to check the gene expression trend in lineage, i am getting a blank plot. Also the heatmap which is plotted to get the gene expression, is blank. 

Please suggest what can be the reason, and any alternative which can be implemented.
Thank you so much in advance.

**Comment by Marius1311** [comment]
Hi @sidrahmaryam, let's start at the beginning: you report that you see differences between running the basic scvelo workflow (I take it you're using scVelo's stochastic model to compute velocities) and the dynamical model workflow. If that's the case, then this seems to be an scvelo issue, not a cellrank issue and I would ask you to move the issue there - cellrank is not a part of scvelo. 

The other issues you mention most likely derive from the fact that there is a problem with the dynamical-model velocities from scVelo in your biological application. Please, make sure that you get more or less meaningful velocities before running CellRank. CellRank can cope with noise in RNA velocity - however, if your velocities are systematically wrong, then so will be any method that builds on these (like CellRank).

**Comment by Marius1311** [comment]
@sidrahmaryam , did my answer above help?

**Comment by sidrahmaryam** [comment]
@Marius1311 Thank you so much for your response. Sorry for replying late.
Sure I will sanity check once with the velocities being calculated, and would try as suggested.

**Comment by Marius1311** [comment]
Hi @sidrahmaryam , I will close this issue here, feel free to re-open this in the main cellrank repo: https://github.com/theislab/cellrank

You accidentally posted in the cellrank_notebooks repo - it doesn't really matter, only that I don't check this regularly and I may miss one of your comments.
