### ISSUE TITLE
CytoTRACE tutorial outdated

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank_notebooks#43]
## Description

If I am not mistaken, the API for the CytoTRACE kernel changed with theislab/cellrank#791. Previously, the all statistics were calculated when instantiating the kernel, _i.e._,

```python
ctk = CytoTRACEKernel(adata)
```

To achieve the same behaviour, the following code needs to be used

```python
ctk = CytoTRACEKernel(adata).compute_cytotrace()
```

The tutorial has not yet been updated accordingly.

**Comment by michalk8** [comment]
closed via #65
