### ISSUE TITLE
Update time series tutorial

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_notebooks#44]
Currently, our tutorial subsamples the data to 25% of the cells to speed up computations - rather than doing that, we should use our adaptive thresholding scheme, which is currently not used. Would be good to see whether this changes results - it's okay if it does actually, subsampling to 1/4 of the data is quite a reduction in cell number.

**Comment by michalk8** [comment]
closed via https://github.com/theislab/cellrank_notebooks/pull/64
