### ISSUE TITLE
Linking to Tutorials does not really work

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_notebooks#5]
When I visit https://cellrank.readthedocs.io/en/latest/index.html, I can see two tutorials, advanced and basic. However, when I click on e.g. API, then there is only one tutorial (Pancreas) left. Do you have an idea of that's going wong here? This happens in both repos (cellrank & notebooks)

**Comment by michalk8** [comment]
I don't know what you mean exactly, I see both of them, always. See the attached picture.
![Screenshot from 2020-03-23 12-52-02](https://user-images.githubusercontent.com/46717574/77314049-3c2bf800-6d05-11ea-9b79-f23d6d5bda7f.png)

**Comment by Marius1311** [comment]
This is what I see when I click on API:
![Screenshot 2020-03-23 at 15 01 20](https://user-images.githubusercontent.com/24494650/77324554-363f1280-6d17-11ea-8469-21ac47337da5.png)

**Comment by Marius1311** [comment]
Note that I'm not doing this locally but for the docs hosted on readthedocs.org

**Comment by Marius1311** [comment]
This happens when I click on the API or on the Pancreas Basic tutorial.

**Comment by michalk8** [comment]
I'm not really sure why that happens, I don't have that problem. I've updated the docs to use sphinx version > 2, maybe it has fixed things for you. This can also be browser related issue (you using safari + not using adblock).

**Comment by Marius1311** [comment]
It's fixed now for me! Must have been the sphinx version then. Thanks!
