### ISSUE TITLE
Update the basic tutorial

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_notebooks#6]
I have updated the basic tutorial, however, I wasn't able to update the lineage trends. I was thinking whether you could maybe fit the gene expression trends using a python module, so that I can also update them? Or is it the case that we always get much better results using R's mcgv package?

**Comment by michalk8** [comment]
mgcv produces the best result, I will update the tutorial.

**Comment by Marius1311** [comment]
Thanks!

**Comment by Marius1311** [comment]
When you update the tutorial, could you please add before computing latent time that informs the user that for this to work, they need to install scvelo from source, link to https://scvelo.readthedocs.io/getting_started.html and tell them how to do it: `pip install git+https://github.com/theislab/scvelo`

**Comment by michalk8** [comment]
Done via #8

**Comment by Marius1311** [comment]
Fantastic, thanks!
